#测试环境
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #用于连接本地数据库测试是否能正确运行
    url: jdbc:mysql://localhost:3306/clothes_mall_database?userSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password:  admin123
    hikari:
      max-lifetime: 600000  #连接的最大生命周期，表示一个连接在被关闭之前的最长使用时间。设置为30分钟（1800000毫秒）
      connection-test-query: "SELECT 1"
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password:
      database: 0
      connect-timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 20
          # 连接池中的最小空闲连接
          min-idle: 0